import { PrismaClient } from "./generated/client";
import { PrismaPg } from "@prisma/adapter-pg";

// Create Prisma client instance for seeding
const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({
  adapter,
});

// Common foods with realistic nutrition data (per 100g)
// Source: USDA FoodData Central
const commonFoods = [
  // Proteins
  {
    name: "Grilled Chicken Breast",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 74,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Salmon Fillet",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 208,
    proteinG: 26,
    carbsG: 0,
    fatG: 12,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 59,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Ground Beef (90% lean)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 176,
    proteinG: 25,
    carbsG: 0,
    fatG: 10,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 75,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Whole Egg",
    brand: null,
    servingSizeG: 50,
    servingSizeUnit: "g (1 large egg)",
    caloriesPer100g: 143,
    proteinG: 13,
    carbsG: 1,
    fatG: 10,
    fiberG: 0,
    sugarG: 1,
    sodiumMg: 124,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Greek Yogurt (Plain, Nonfat)",
    brand: null,
    servingSizeG: 170,
    servingSizeUnit: "g (1 container)",
    caloriesPer100g: 59,
    proteinG: 10,
    carbsG: 3.6,
    fatG: 0.4,
    fiberG: 0,
    sugarG: 3.2,
    sodiumMg: 36,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Tuna (Canned in Water)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 116,
    proteinG: 26,
    carbsG: 0,
    fatG: 0.8,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 247,
    source: "user" as const,
    verified: true,
  },

  // Carbs
  {
    name: "Brown Rice (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 111,
    proteinG: 2.6,
    carbsG: 23,
    fatG: 0.9,
    fiberG: 1.8,
    sugarG: 0.4,
    sodiumMg: 5,
    source: "user" as const,
    verified: true,
  },
  {
    name: "White Rice (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 130,
    proteinG: 2.7,
    carbsG: 28,
    fatG: 0.3,
    fiberG: 0.4,
    sugarG: 0.1,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Quinoa (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 120,
    proteinG: 4.4,
    carbsG: 21,
    fatG: 1.9,
    fiberG: 2.8,
    sugarG: 0.9,
    sodiumMg: 7,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Sweet Potato (Baked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 90,
    proteinG: 2,
    carbsG: 21,
    fatG: 0.2,
    fiberG: 3.3,
    sugarG: 6.5,
    sodiumMg: 36,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Oatmeal (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 71,
    proteinG: 2.5,
    carbsG: 12,
    fatG: 1.5,
    fiberG: 1.7,
    sugarG: 0.3,
    sodiumMg: 49,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Whole Wheat Bread",
    brand: null,
    servingSizeG: 28,
    servingSizeUnit: "g (1 slice)",
    caloriesPer100g: 247,
    proteinG: 13,
    carbsG: 41,
    fatG: 3.4,
    fiberG: 6.8,
    sugarG: 5.6,
    sodiumMg: 400,
    source: "user" as const,
    verified: true,
  },

  // Vegetables
  {
    name: "Broccoli (Steamed)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 35,
    proteinG: 2.4,
    carbsG: 7,
    fatG: 0.4,
    fiberG: 3.3,
    sugarG: 1.4,
    sodiumMg: 41,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Spinach (Raw)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 23,
    proteinG: 2.9,
    carbsG: 3.6,
    fatG: 0.4,
    fiberG: 2.2,
    sugarG: 0.4,
    sodiumMg: 79,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Mixed Vegetables (Frozen)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 65,
    proteinG: 2.6,
    carbsG: 13,
    fatG: 0.3,
    fiberG: 3.8,
    sugarG: 4.5,
    sodiumMg: 43,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Bell Pepper (Raw)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 26,
    proteinG: 0.9,
    carbsG: 6,
    fatG: 0.3,
    fiberG: 1.7,
    sugarG: 4.2,
    sodiumMg: 2,
    source: "user" as const,
    verified: true,
  },

  // Fruits
  {
    name: "Banana",
    brand: null,
    servingSizeG: 120,
    servingSizeUnit: "g (1 medium)",
    caloriesPer100g: 89,
    proteinG: 1.1,
    carbsG: 23,
    fatG: 0.3,
    fiberG: 2.6,
    sugarG: 12,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Apple",
    brand: null,
    servingSizeG: 182,
    servingSizeUnit: "g (1 medium)",
    caloriesPer100g: 52,
    proteinG: 0.3,
    carbsG: 14,
    fatG: 0.2,
    fiberG: 2.4,
    sugarG: 10,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Blueberries",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 57,
    proteinG: 0.7,
    carbsG: 14,
    fatG: 0.3,
    fiberG: 2.4,
    sugarG: 10,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Strawberries",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 32,
    proteinG: 0.7,
    carbsG: 7.7,
    fatG: 0.3,
    fiberG: 2,
    sugarG: 4.9,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },

  // Fats & Nuts
  {
    name: "Almonds",
    brand: null,
    servingSizeG: 28,
    servingSizeUnit: "g (1 oz)",
    caloriesPer100g: 579,
    proteinG: 21,
    carbsG: 22,
    fatG: 50,
    fiberG: 12,
    sugarG: 4.4,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Peanut Butter",
    brand: null,
    servingSizeG: 32,
    servingSizeUnit: "g (2 tbsp)",
    caloriesPer100g: 588,
    proteinG: 25,
    carbsG: 20,
    fatG: 50,
    fiberG: 8,
    sugarG: 9,
    sodiumMg: 476,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Avocado",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 160,
    proteinG: 2,
    carbsG: 8.5,
    fatG: 15,
    fiberG: 6.7,
    sugarG: 0.7,
    sodiumMg: 7,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Olive Oil",
    brand: null,
    servingSizeG: 14,
    servingSizeUnit: "g (1 tbsp)",
    caloriesPer100g: 884,
    proteinG: 0,
    carbsG: 0,
    fatG: 100,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 2,
    source: "user" as const,
    verified: true,
  },

  // Dairy
  {
    name: "Whole Milk",
    brand: null,
    servingSizeG: 244,
    servingSizeUnit: "g (1 cup)",
    caloriesPer100g: 61,
    proteinG: 3.2,
    carbsG: 4.8,
    fatG: 3.3,
    fiberG: 0,
    sugarG: 5.1,
    sodiumMg: 43,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Cheddar Cheese",
    brand: null,
    servingSizeG: 28,
    servingSizeUnit: "g (1 oz)",
    caloriesPer100g: 403,
    proteinG: 25,
    carbsG: 1.3,
    fatG: 33,
    fiberG: 0,
    sugarG: 0.5,
    sodiumMg: 621,
    source: "user" as const,
    verified: true,
  },

  // Other
  {
    name: "Protein Powder (Whey)",
    brand: null,
    servingSizeG: 30,
    servingSizeUnit: "g (1 scoop)",
    caloriesPer100g: 400,
    proteinG: 80,
    carbsG: 6.7,
    fatG: 6.7,
    fiberG: 0,
    sugarG: 3.3,
    sodiumMg: 333,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Pasta (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 131,
    proteinG: 5,
    carbsG: 25,
    fatG: 1.1,
    fiberG: 1.8,
    sugarG: 0.6,
    sodiumMg: 1,
    source: "user" as const,
    verified: true,
  },
  {
    name: "Black Beans (Cooked)",
    brand: null,
    servingSizeG: 100,
    servingSizeUnit: "g",
    caloriesPer100g: 132,
    proteinG: 8.9,
    carbsG: 24,
    fatG: 0.5,
    fiberG: 8.7,
    sugarG: 0.3,
    sodiumMg: 2,
    source: "user" as const,
    verified: true,
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Check if foods already exist
  const existingCount = await prisma.foodItem.count();
  if (existingCount > 0) {
    console.log(`⚠️  Database already has ${existingCount} food items.`);
    console.log("Skipping seed to avoid duplicates.");
    return;
  }

  // Insert all foods
  console.log(`📦 Inserting ${commonFoods.length} common foods...`);

  for (const food of commonFoods) {
    await prisma.foodItem.create({
      data: food,
    });
  }

  console.log("✅ Seed completed successfully!");
  console.log(`   Added ${commonFoods.length} food items to the database.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:");
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
