version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: ./Dockerfile.portfolio
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  cookbook:
    container_name: cookbook
    build:
      context: .
      dockerfile: ./Dockerfile.cookbook
    restart: always
    ports:
      - 3002:3000
    networks:
      - app_network
  tanstack:
    container_name: tanstack
    build:
      context: .
      dockerfile: ./Dockerfile.tanstack
    restart: always
    ports:
      - 3003:3003
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
