/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SleepIndexRouteImport } from './routes/sleep/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as FastingIndexRouteImport } from './routes/fasting/index'
import { Route as ExerciseIndexRouteImport } from './routes/exercise/index'
import { Route as DiaryIndexRouteImport } from './routes/diary/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AchievementsIndexRouteImport } from './routes/achievements/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepIndexRoute = SleepIndexRouteImport.update({
  id: '/sleep/',
  path: '/sleep/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sleep/index.lazy').then((d) => d.Route))
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/progress/index.lazy').then((d) => d.Route),
)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/onboarding/index.lazy').then((d) => d.Route),
)
const FastingIndexRoute = FastingIndexRouteImport.update({
  id: '/fasting/',
  path: '/fasting/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fasting/index.lazy').then((d) => d.Route))
const ExerciseIndexRoute = ExerciseIndexRouteImport.update({
  id: '/exercise/',
  path: '/exercise/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/exercise/index.lazy').then((d) => d.Route),
)
const DiaryIndexRoute = DiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/diary/index.lazy').then((d) => d.Route))
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/achievements/index.lazy').then((d) => d.Route),
)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/achievements': typeof AchievementsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/diary': typeof DiaryIndexRoute
  '/exercise': typeof ExerciseIndexRoute
  '/fasting': typeof FastingIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/sleep': typeof SleepIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/achievements': typeof AchievementsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/diary': typeof DiaryIndexRoute
  '/exercise': typeof ExerciseIndexRoute
  '/fasting': typeof FastingIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/sleep': typeof SleepIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diary/': typeof DiaryIndexRoute
  '/exercise/': typeof ExerciseIndexRoute
  '/fasting/': typeof FastingIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/sleep/': typeof SleepIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/achievements'
    | '/dashboard'
    | '/diary'
    | '/exercise'
    | '/fasting'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/sleep'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/achievements'
    | '/dashboard'
    | '/diary'
    | '/exercise'
    | '/fasting'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/sleep'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/achievements/'
    | '/dashboard/'
    | '/diary/'
    | '/exercise/'
    | '/fasting/'
    | '/onboarding/'
    | '/profile/'
    | '/progress/'
    | '/sleep/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DiaryIndexRoute: typeof DiaryIndexRoute
  ExerciseIndexRoute: typeof ExerciseIndexRoute
  FastingIndexRoute: typeof FastingIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  SleepIndexRoute: typeof SleepIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep/': {
      id: '/sleep/'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasting/': {
      id: '/fasting/'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof FastingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/': {
      id: '/exercise/'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/': {
      id: '/diary/'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DiaryIndexRoute: DiaryIndexRoute,
  ExerciseIndexRoute: ExerciseIndexRoute,
  FastingIndexRoute: FastingIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  SleepIndexRoute: SleepIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
